### ISSUE TITLE
Add options to only run pre-push on some branches ('protected' ones)

### ISSUE THREAD

**Issue by Augustin82** [royriojas/prepush#8]
Allow running the prepush script only for some branches, possibly via a config such as:
```
"prepush": {
  "branches": [
    "master",
    "preprod"
  ]
}
```

**Comment by Augustin82** [comment]
Apologies: apparently it exists but is not documented.

For those interested, it is possible to use the following:
```
"prepush": {
  "applyToBranch": string_or_array_to_whitelist,
  "ignoreBranch": string_or_array_to_blacklist,
}
```

**Comment by royriojas** [comment]
hi @Augustin82 sorry, would you mind to make PR for the documentation? that would be awesome if you can. Thank you

**Comment by Augustin82** [comment]
Will do!

**Comment by Augustin82** [comment]
Done in #9 =)
